### ISSUE TITLE
Do příště

### ISSUE THREAD

**Issue by fprochazka** [fprochazka/fi-muni-PB138-2016#27]
Minule #13
- @VikiVozarova 
  - [ ] #23 Naučit se pracovat s authentizací ve Springu
  - [ ] #24 Datové struktury pro http api
- @mbamburova 
  - [x] #22 rozběhat persistenci
- @fprochazka
  - [x] #25 Design Clienta
  - [x] #26 Napsat akce/reducery/store a fetchování dat pro drilly z mock serveru apiary
- @sonicka 
  - [x] #29 Načítání otázek z odpovedníků IS
